trigger:
  none
#  branches:
#    include:
#    - main

pr:
  branches:
    include:
    - main

parameters:
- name: targetEnvironment
  displayName: Target environment
  type: string
  default: dev
  values:
  - dev
  - test
  - prod
- name: backendConfigFile
  type: string
  default: backend.hcl
- name: tfvarsFile
  type: string
  default: terraform.tfvars
- name: deploy_storage_account
  displayName: 'Deploy Storage Account'
  type: boolean
  default: false
- name: 'deploy_loganalysticsworkspace'
  displayName: 'Deploy Log Analytics Workspace'
  type: boolean
  default: false
- name: 'deploy_keyvault'
  displayName: 'Deploy Keyvault'
  type: boolean
  default: false
- name: 'deploy_containerregistry'
  displayName: 'Deploy Container Registry'
  type: boolean
  default: false
- name: 'deploy_applicationInsights'
  displayName: 'Deploy Application Insights'
  type: boolean
  default: false
- name: 'deploy_machinelearning'
  displayName: 'Deploy Machine Learning'
  type: boolean
  default: false
- name: 'deploy_synapse'
  displayName: 'Deploy Synapse'
  type: boolean
  default: false
- name: 'deploy_machinelearningComputeInstance'
  displayName: 'Deploy Machine Learning Compute Instance'
  type: boolean
  default: false
- name: 'deploy_machinelearningComputeCluster'
  displayName: 'Deploy Machine Learning Compute Cluster'
  type: boolean
  default: false
- name: 'deploy_LogicApp'
  displayName: 'Deploy Logic App'
  type: boolean
  default: false  
- name: 'deploy_data_factory'
  displayName: 'Deploy Data Factory'
  type: boolean
  default: false  
- name: 'deploy_app_service'
  displayName: 'Deploy App Service'
  type: boolean
  default: false    
- name: 'deploy_app_service_plan'
  displayName: 'Deploy App Service Plan'
  type: boolean
  default: false  
- name: 'deploy_cognitive_services'
  displayName: 'Deploy Cognitive Services'
  type: boolean
  default: false  
- name: 'deploy_container_apps'
  displayName: 'Deploy Container Apps'
  type: boolean
  default: false  
- name: 'deploy_resource_group'
  displayName: 'Deploy Resource Group'
  type: boolean
  default: false  
- name: 'deploy_virtual_network'
  displayName: 'Deploy Virtual Network'
  type: boolean
  default: false  

pool:
 name: 'MyPipelines'
 vmImage: 'ubuntu-latest'

variables:
- group: subscripEnv
- name: azureServiceConnectionName
  value: 'YOUR_DEVOPS_SERVICE_CONNECTION_NAME' 
- name: terraformVersion
  value: '1.15.8'

stages:
- stage: Validate
  displayName: Validate
  jobs:
  - template: pipelines/templates/terraform-validate.yml
    parameters:
      environmentName: ${{ parameters.targetEnvironment }}
      environmentPath: environments/${{ parameters.targetEnvironment }}
      backendConfigFile: ${{ parameters.backendConfigFile }}
      tfvarsFile: ${{ parameters.tfvarsFile }}
      service_connection: ${{ variables.azureServiceConnectionName }}
      terraformVersion: ${{ variables.terraformVersion }}
      deploy_storage_account: ${{ parameters.deploy_storage_account }}
      deploy_loganalysticsworkspace: ${{ parameters.deploy_loganalysticsworkspace }}
      deploy_keyvault: ${{ parameters.deploy_keyvault }}
      deploy_containerregistry: ${{ parameters.deploy_containerregistry }}
      deploy_applicationInsights: ${{ parameters.deploy_applicationInsights }}
      deploy_machinelearning: ${{ parameters.deploy_machinelearning }}
      deploy_synapse: ${{ parameters.deploy_synapse }}
      deploy_machinelearningComputeInstance: ${{ parameters.deploy_machinelearningComputeInstance }}
      deploy_machinelearningComputeCluster: ${{ parameters.deploy_machinelearningComputeCluster }}
      deploy_LogicApp: ${{ parameters.deploy_LogicApp }}
      deploy_data_factory: ${{ parameters.deploy_data_factory }}
      deploy_app_service: ${{ parameters.deploy_app_service }}
      deploy_app_service_plan: ${{ parameters.deploy_app_service_plan }}
      deploy_cognitive_services: ${{ parameters.deploy_cognitive_services }}
      deploy_container_apps: ${{ parameters.deploy_container_apps }}
      deploy_resource_group: ${{ parameters.deploy_resource_group }}
      deploy_virtual_network: ${{ parameters.deploy_virtual_network }}
- stage: Plan
  displayName: Plan
  jobs:
  - template: pipelines/templates/terraform-plan.yml
    parameters:
      environmentName: ${{ parameters.targetEnvironment }}
      environmentPath: environments/${{ parameters.targetEnvironment }}
      backendConfigFile: ${{ parameters.backendConfigFile }}
      tfvarsFile: ${{ parameters.tfvarsFile }}
      service_connection: ${{ variables.azureServiceConnectionName }}
      terraformVersion: ${{ variables.terraformVersion }}
      deploy_storage_account: ${{ parameters.deploy_storage_account }}
      deploy_loganalysticsworkspace: ${{ parameters.deploy_loganalysticsworkspace }}
      deploy_keyvault: ${{ parameters.deploy_keyvault }}
      deploy_containerregistry: ${{ parameters.deploy_containerregistry }}
      deploy_applicationInsights: ${{ parameters.deploy_applicationInsights }}
      deploy_machinelearning: ${{ parameters.deploy_machinelearning }}
      deploy_synapse: ${{ parameters.deploy_synapse }}
      deploy_machinelearningComputeInstance: ${{ parameters.deploy_machinelearningComputeInstance }}
      deploy_machinelearningComputeCluster: ${{ parameters.deploy_machinelearningComputeCluster }}
      deploy_LogicApp: ${{ parameters.deploy_LogicApp }}
      deploy_data_factory: ${{ parameters.deploy_data_factory }}
      deploy_app_service: ${{ parameters.deploy_app_service }}
      deploy_app_service_plan: ${{ parameters.deploy_app_service_plan }}
      deploy_cognitive_services: ${{ parameters.deploy_cognitive_services }}
      deploy_container_apps: ${{ parameters.deploy_container_apps }}
      deploy_resource_group: ${{ parameters.deploy_resource_group }}
      deploy_virtual_network: ${{ parameters.deploy_virtual_network }}
- stage: Apply
  displayName: Apply
  jobs:
  - template: pipelines/templates/terraform-apply.yml
    parameters:
      environmentName: ${{ parameters.targetEnvironment }}
      environmentPath: environments/${{ parameters.targetEnvironment }}
      backendConfigFile: ${{ parameters.backendConfigFile }}
      tfvarsFile: ${{ parameters.tfvarsFile }}
      service_connection: ${{ variables.azureServiceConnectionName }}
      terraformVersion: ${{ variables.terraformVersion }}
      deploy_storage_account: ${{ parameters.deploy_storage_account }}
      deploy_loganalysticsworkspace: ${{ parameters.deploy_loganalysticsworkspace }}
      deploy_keyvault: ${{ parameters.deploy_keyvault }}
      deploy_containerregistry: ${{ parameters.deploy_containerregistry }}
      deploy_applicationInsights: ${{ parameters.deploy_applicationInsights }}
      deploy_machinelearning: ${{ parameters.deploy_machinelearning }}
      deploy_synapse: ${{ parameters.deploy_synapse }}
      deploy_machinelearningComputeInstance: ${{ parameters.deploy_machinelearningComputeInstance }}
      deploy_machinelearningComputeCluster: ${{ parameters.deploy_machinelearningComputeCluster }}
      deploy_LogicApp: ${{ parameters.deploy_LogicApp }}
      deploy_data_factory: ${{ parameters.deploy_data_factory }}
      deploy_app_service: ${{ parameters.deploy_app_service }}
      deploy_app_service_plan: ${{ parameters.deploy_app_service_plan }}
      deploy_cognitive_services: ${{ parameters.deploy_cognitive_services }}
      deploy_container_apps: ${{ parameters.deploy_container_apps }}
      deploy_resource_group: ${{ parameters.deploy_resource_group }}
      deploy_virtual_network: ${{ parameters.deploy_virtual_network }}